### ISSUE TITLE
It doesn't expose the highest resolution available for the photo

### ISSUE THREAD

**Issue by JenieX** [LBreda/instagram_unprotect#1]
Probably because of the `srcset` attribute. In my case it seems like the `src` attribute holds the highest resolution.

Removing the `srcset` attribute doesnt solve it, because it gets recreated once removed, in my testing.
Creating a new image element with the same attributes, except the `srcset` attribute, seems to do the trick.

**Comment by LBreda** [comment]
Solved the issue.
